apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: jenkins-backup
  namespace: velero
spec:
  schedule: '* 5 * * *'
  template:
    hooks: {}
    includedNamespaces:
    - jenkins
    snapshotVolumes: false
    ttl: 720h0m0s
  useOwnerReferencesInBackup: false

